---
name: Release

on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: false
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v5
      with:
        images: kong/httpbin
        tags: |
          type=semver,pattern={{version}},value=${{ steps.tag.outputs.tag }}
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      uses: docker/bake-action@5ca506d06f70338a4968df87fd8bfee5cbfb84c7 # v6
      with:
        source: .
        push: 'true'
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build
